ALTER TABLE t_hi_addons_ratemaster DISABLE KEYS;
INSERT INTO t_hi_addons_ratemaster VALUES (1,'Travel Protect cover','TPDOC','Travel Protect','Y','Y','N','N','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (2,'Premium Waiver','PWAIV','Premium Waiver','Y','Y','N','N','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (3,'EMI Protection Cover','EMIP','EMI Protection','Y','Y','N','N','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (4,'Super No Claim Bonus','SNCB','Super No Claim Bonus','Y','Y','N','N','Y','Y','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (5,'Non-Medical Expense Waiver','WNME','Non- Medical Expense','Y','Y','N','N','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (6,'OPD expense Benefits','OPDE','OPD Expense','Y','Y','N','N','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (7,'Reduction In Maternity waiting Period','RIMWP','Reduction in Maternity Waiting Period','N','N','N','N','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (8,'Future Secure','FTSE','Future Secure','N','N','Y','Y','Y','Y','Y','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (9,'Cancer Hospitalization Cover',NULL,'Cancer Hospitalization Booster','N','N','Y','Y','N','N','Y','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (10,'Vaccine Cover','RVCV','Vaccine cover','N','N','Y','Y','Y','Y','Y','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (11,'Personal Accident Cover',NULL,'Personal Accident Cover (AD, PTD)','N','N','Y','Y','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (12,'Critical Illness Cover',NULL,'Critical Illness Cover','N','N','Y','Y','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (13,'Hospital Cash Benefit Cover',NULL,'Hospital Cash Benefit','N','N','Y','Y','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (14,'Room Type',NULL,NULL,'N','N','Y','Y','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (15,'International Coverage for Major Illness Cover',NULL,'International Coverage for major illnesses','N','N','Y','Y','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (16,'Waiver Co pay',NULL,'Waiver of Mandatory Co-payment','N','N','N','Y','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (17,'Unlimited Reload of Sum Insured',NULL,'Unlimited Reload of Sum Insured','N','N','N','N','Y','Y','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (18,'Nursing at Home',NULL,'Nursing at Home','N','N','N','N','N','N','Y','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (19,'Lifestyle Support Equipment',NULL,'Lifestyle support equipment','N','N','N','N','N','N','Y','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (20,'Portable Medical Equipment',NULL,'Portable medical equipment','N','N','N','N','N','N','Y','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (21,'Advanced Health Check Up',NULL,'Advance Health Check-up','N','N','N','N','N','N','Y','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (22,'Room Upgrade',NULL,'Room Upgrade','N','N','N','N','N','N','N','N','N');
INSERT INTO t_hi_addons_ratemaster VALUES (23,'Tele Opd Consultation','TELEOPD','Tele – OPD consultation','N','N','Y','Y','Y','Y','Y','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (24,'Durable Equipment Cover',NULL,'Durable Equipment Cover','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (25,'Second Medical Opinion for listed Major Illness per person',NULL,'Second Medical Opinion for listed Major Illness per person','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (26,'Annual Screening Package for Cancer Diagnosed Patients',NULL,'Annual Screening Package for Cancer Diagnosed Patients','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (27,'Compassionate Visit',NULL,'Compassionate Visit','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (28,'Cancer Hospitalization Booster',NULL,'Cancer Hospitalization Booster','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (29,'Per Claim Deductible',NULL,'Per Claim Deductible','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (30,'Preferred Provider Network',NULL,'Preferred Provider Network','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (31,'Chronic Care',NULL,'Chronic Care','N','N','N','N','N','N','N','N','Y');
INSERT INTO t_hi_addons_ratemaster VALUES (32,'Chronic Management Program (OPD)',NULL,'Chronic Management Program (OPD)','N','N','N','N','N','N','N','N','Y');
INSERT INTO t_hi_addons_ratemaster VALUES (33,'Annual Health Check-up',NULL,'Annual Health Check-up','N','N','N','N','N','N','N','Y','N');
INSERT INTO t_hi_addons_ratemaster VALUES (34,'Room Rent Type',NULL,'Room Rent Type','N','N','N','N','N','N','N','Y','N');
ALTER TABLE t_hi_addons_ratemaster ENABLE KEYS ;