RENAME TABLE t_hi_consolidated_master to t_hi_consolidated_master_backup_03Mar;

CREATE TABLE t_hi_consolidated_master (
  id int DEFAULT NULL,
  min_age int DEFAULT NULL,
  max_age int DEFAULT NULL,
  sum_insured double DEFAULT NULL,
  deductible double DEFAULT NULL,
  premium_amount double DEFAULT NULL,
  premium_percent float DEFAULT NULL,
  addon_name varchar(100) DEFAULT NULL,
  lob_id int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (1,NULL,NULL,10000,NULL,272,NULL,'Travel Protect cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (2,NULL,NULL,20000,NULL,544,NULL,'Travel Protect cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (3,NULL,NULL,0,NULL,902,NULL,'OPD expense Benefits',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (4,NULL,NULL,500,NULL,369,NULL,'Vaccine Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (5,NULL,NULL,750,NULL,554,NULL,'Vaccine Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (6,NULL,NULL,1000,NULL,738,NULL,'Vaccine Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (7,NULL,NULL,500000,NULL,447,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (8,NULL,NULL,600000,NULL,536,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (9,NULL,NULL,700000,NULL,626,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (10,NULL,NULL,800000,NULL,715,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (11,NULL,NULL,900000,NULL,805,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (12,NULL,NULL,1000000,NULL,894,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (13,NULL,NULL,1500000,NULL,1341,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (14,NULL,NULL,2000000,NULL,1788,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (15,NULL,NULL,2500000,NULL,2235,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (16,NULL,NULL,3000000,NULL,2682,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (17,NULL,NULL,4000000,NULL,3576,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (18,NULL,NULL,5000000,NULL,4470,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (19,NULL,NULL,10000000,NULL,8940,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (20,NULL,NULL,15000000,NULL,13410,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (21,NULL,NULL,20000000,NULL,17880,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (22,NULL,NULL,50000000,NULL,44699,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (23,NULL,NULL,100000000,NULL,89398,NULL,'Personal Accident Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (24,NULL,NULL,0,NULL,376,NULL,'Tele Opd Consultation',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (25,NULL,NULL,0,NULL,3484,NULL,'Reduction In Maternity waiting Period',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (26,18,25,NULL,NULL,NULL,1.13,'EMI Protection Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (27,26,35,NULL,NULL,NULL,1.2,'EMI Protection Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (28,36,40,NULL,NULL,NULL,1.33,'EMI Protection Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (29,41,45,NULL,NULL,NULL,1.41,'EMI Protection Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (30,46,50,NULL,NULL,NULL,1.9,'EMI Protection Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (31,0,0,NULL,NULL,NULL,8.7,'Super No Claim Bonus',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (32,18,25,NULL,NULL,NULL,0.13,'Premium Waiver',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (33,26,35,NULL,NULL,NULL,0.19,'Premium Waiver',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (34,36,40,NULL,NULL,NULL,0.33,'Premium Waiver',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (35,41,45,NULL,NULL,NULL,0.54,'Premium Waiver',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (36,46,50,NULL,NULL,NULL,0.83,'Premium Waiver',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (37,18,45,700000,NULL,NULL,10,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (38,18,45,1000000,NULL,NULL,10,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (39,18,45,1500000,NULL,NULL,7.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (40,18,45,2000000,NULL,NULL,7.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (41,18,45,2500000,NULL,NULL,7.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (42,18,45,3000000,NULL,NULL,7.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (43,18,45,4000000,NULL,NULL,7.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (44,18,45,5000000,NULL,NULL,7.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (45,18,45,7500000,NULL,NULL,3.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (46,18,45,10000000,NULL,NULL,3.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (47,18,45,20000000,NULL,NULL,3.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (48,46,75,700000,NULL,NULL,15,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (49,46,75,1000000,NULL,NULL,15,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (50,46,75,1500000,NULL,NULL,11,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (51,46,75,2000000,NULL,NULL,11,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (52,46,75,2500000,NULL,NULL,11,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (53,46,75,3000000,NULL,NULL,11,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (54,46,75,4000000,NULL,NULL,11,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (55,46,75,5000000,NULL,NULL,11,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (56,46,75,7500000,NULL,NULL,5.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (57,46,75,10000000,NULL,NULL,5.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (58,46,75,20000000,NULL,NULL,5.5,'Durable Equipment Cover',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (59,NULL,NULL,0,NULL,325,NULL,'Compassionate Visit',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (60,18,45,0,NULL,225,NULL,'Annual Screening Package for Cancer Diagnosed Patients',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (61,46,75,0,NULL,451,NULL,'Annual Screening Package for Cancer Diagnosed Patients',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (62,18,50,700000,15000,NULL,9,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (63,18,50,1000000,15000,NULL,9,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (64,18,50,1500000,15000,NULL,5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (65,18,50,2000000,15000,NULL,5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (66,18,50,2500000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (67,18,50,3000000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (68,18,50,4000000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (69,18,50,5000000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (70,18,50,10000000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (71,18,50,20000000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (72,51,75,700000,15000,NULL,6.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (73,51,75,1000000,15000,NULL,6.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (74,51,75,1500000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (75,51,75,2000000,15000,NULL,3.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (76,51,75,2500000,15000,NULL,2.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (77,51,75,3000000,15000,NULL,2.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (78,51,75,4000000,15000,NULL,2.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (79,51,75,5000000,15000,NULL,2.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (80,51,75,10000000,15000,NULL,2.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (81,51,75,20000000,15000,NULL,2.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (82,18,50,700000,25000,NULL,18,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (83,18,50,1000000,25000,NULL,18,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (84,18,50,1500000,25000,NULL,9,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (85,18,50,2000000,25000,NULL,9,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (86,18,50,2500000,25000,NULL,6.8,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (87,18,50,3000000,25000,NULL,6.8,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (88,18,50,4000000,25000,NULL,6.8,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (89,18,50,5000000,25000,NULL,6.8,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (90,18,50,10000000,25000,NULL,6.8,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (91,18,50,20000000,25000,NULL,6.8,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (92,51,75,700000,25000,NULL,13.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (93,51,75,1000000,25000,NULL,13.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (94,51,75,1500000,25000,NULL,6,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (95,51,75,2000000,25000,NULL,6,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (96,51,75,2500000,25000,NULL,4.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (97,51,75,3000000,25000,NULL,4.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (98,51,75,4000000,25000,NULL,4.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (99,51,75,5000000,25000,NULL,4.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (100,51,75,10000000,25000,NULL,4.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (101,51,75,20000000,25000,NULL,4.5,'Per Claim Deductible',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (102,NULL,NULL,0,NULL,100,NULL,'Second Medical Opinion for listed Major Illness per person',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (103,18,45,500000,NULL,NULL,3,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (104,18,45,700000,NULL,NULL,3,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (105,18,45,1000000,NULL,NULL,3,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (106,18,45,1500000,NULL,NULL,2,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (107,18,45,2000000,NULL,NULL,2,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (108,18,45,2500000,NULL,NULL,2,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (109,18,45,3000000,NULL,NULL,2,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (110,18,45,4000000,NULL,NULL,2,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (111,18,45,5000000,NULL,NULL,2,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (112,18,45,7500000,NULL,NULL,1.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (113,18,45,10000000,NULL,NULL,1.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (114,18,45,20000000,NULL,NULL,1.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (115,46,75,500000,NULL,NULL,5.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (116,46,75,700000,NULL,NULL,5.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (117,46,75,1000000,NULL,NULL,5.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (118,46,75,1500000,NULL,NULL,4.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (119,46,75,2000000,NULL,NULL,4.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (120,46,75,2500000,NULL,NULL,4.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (121,46,75,3000000,NULL,NULL,4.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (122,46,75,4000000,NULL,NULL,4.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (123,46,75,5000000,NULL,NULL,4.5,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (124,46,75,7500000,NULL,NULL,3,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (125,46,75,10000000,NULL,NULL,3,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (126,46,75,20000000,NULL,NULL,3,'Cancer Hospitalization Booster',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (127,18,35,200000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (128,18,35,500000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (129,18,35,700000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (130,18,35,1000000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (131,18,35,1500000,NULL,NULL,612,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (132,18,35,2000000,NULL,NULL,612,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (133,18,35,2500000,NULL,NULL,612,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (134,18,35,5000000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (135,18,35,7500000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (136,18,35,10000000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (137,18,35,20000000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (138,36,45,200000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (139,36,45,500000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (140,36,45,700000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (141,36,45,1000000,NULL,NULL,432,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (142,36,45,1500000,NULL,NULL,612,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (143,36,45,2000000,NULL,NULL,612,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (144,36,45,2500000,NULL,NULL,612,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (145,36,45,5000000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (146,36,45,7500000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (147,36,45,10000000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (148,36,45,20000000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (149,46,55,200000,NULL,NULL,576,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (150,46,55,500000,NULL,NULL,576,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (151,46,55,700000,NULL,NULL,576,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (152,46,55,1000000,NULL,NULL,576,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (153,46,55,1500000,NULL,NULL,765,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (154,46,55,2000000,NULL,NULL,765,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (155,46,55,2500000,NULL,NULL,765,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (156,46,55,5000000,NULL,NULL,1275,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (157,46,55,7500000,NULL,NULL,1275,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (158,46,55,10000000,NULL,NULL,1275,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (159,46,55,20000000,NULL,NULL,1275,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (160,56,75,200000,NULL,NULL,720,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (161,56,75,500000,NULL,NULL,720,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (162,56,75,700000,NULL,NULL,720,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (163,56,75,1000000,NULL,NULL,720,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (164,56,75,1500000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (165,56,75,2000000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (166,56,75,2500000,NULL,NULL,1020,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (167,56,75,5000000,NULL,NULL,1700,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (168,56,75,7500000,NULL,NULL,1700,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (169,56,75,10000000,NULL,NULL,1700,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (170,56,75,20000000,NULL,NULL,1700,'Annual Health Check-up',4);
INSERT INTO t_hi_consolidated_master (id, min_age, max_age, sum_insured, deductible, premium_amount, premium_percent, addon_name, lob_id) VALUES (171,0,0,NULL,NULL,NULL,10,'Preferred Provider Network',4);
